name: Test Android Project

on:
  workflow_dispatch:    
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'fastlane/**'
      - /.github/workflows/build.yml
      - /.github/workflows/test.yml
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'fastlane/**'



jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
